version: "3.9"

services:
  token-app:
    container_name: token-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - gateway
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  gateway:
    driver: bridge

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/token-chats/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/token-chats/dhparam/
      o: bind
