const {
  getName,
  getOwner,
  isOwner,
  isPaused,
  totalSupply,
  totalIssued,
  totalRedeemed,
  allowance,
  balanceOf,
  getUsersList,
  getAdminList,
  getAuthorizerList,
  getBlackListed,
  isUserListed,
  isAdmin,
  isAuthorizer,
  isBlackListed
} = require("./getterAPIController");

const {
  addAdmin,
  removeAdmin,
  addAuthorizer,
  removeAuthorizer,
  addBlackList,
  removeBlackList,
  addUserList,
  removeUserList,
  createAccount,
  pause,
  unpause,
  initiateOwnershipTransfer,
  completeOwnershipTransfer,
  cancelOwnershipTransfer,
  setParams,
  approve,
  disApprove,
  transferAdmin,
  transfers,
  minting,
  redeeming,
  transferFrom,
  destroyBlackFunds,
  increaseGasPrice
} = require("./setterAPIController");

module.exports = {
  allowance,
  balanceOf,
  getName,
  getOwner,
  getUsersList,
  getAdminList,
  getAuthorizerList,
  getBlackListed,
  totalSupply,
  totalIssued,
  totalRedeemed,
  isOwner,
  isPaused,
  isUserListed,
  isAdmin,
  isAuthorizer,
  isBlackListed,


  addAdmin,
  createAccount,
  addAuthorizer,
  addBlackList,
  addUserList,
  removeAdmin,
  removeAuthorizer,
  removeBlackList,
  removeUserList,
  pause,
  unpause,
  initiateOwnershipTransfer,
  completeOwnershipTransfer,
  cancelOwnershipTransfer,
  setParams,
  approve,
  disApprove,
  transferAdmin,
  transfers,
  minting,
  redeeming,
  transferFrom,
  destroyBlackFunds,
  increaseGasPrice
};
